name: stripe
version: 4.11.0
description: A simple Stripe API wrapper, that is meant to be used on the server.
homepage: https://github.com/enyo/stripe-dart
documentation: https://github.com/enyo/stripe-dart/blob/main/README.md
environment:
  sdk: ^3.0.0
dependencies:
  crypto: ^3.0.0
  http: ^0.13.1
  json_annotation: ^4.9.0
  meta: ^1.1.7
  logging: ^1.0.1
  dio: ^5.1.2
dev_dependencies:
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  test: ^1.3.0
  mocktail: ^0.3.0
  lints: ^1.0.1
